version: "3.9"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://localhost:27017/expense-manager
      - PORT=3000
      - SIGNATURE=b8942bcc5bc3c417813ea24231eab15673dbc620e2cf72bcbf9c1df510701a74
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
